
export const propfindXml = `<?xml version="1.0" encoding="utf-8"?>
<D:multistatus
	xmlns:D="DAV:">
	<D:response>
		<D:href>http://localhost:4200/webdav/animals/</D:href>
		<D:propstat>
			<D:status>HTTP/1.1 200 OK</D:status>
			<D:prop>
				<D:getlastmodified>Wed, 28 Sep 2022 01:36:33 GMT</D:getlastmodified>
				<D:lockdiscovery/>
					<D:supportedlock>
						<D:lockentry>
							<D:lockscope>
								<D:exclusive/>
							</D:lockscope>
							<D:locktype>
								<D:write/>
							</D:locktype>
						</D:lockentry>
						<D:lockentry>
							<D:lockscope>
								<D:shared/>
							</D:lockscope>
							<D:locktype>
								<D:write/>
							</D:locktype>
						</D:lockentry>
					</D:supportedlock>
					<D:creationdate>2022-09-28T01:05:20+04:00</D:creationdate>
					<D:resourcetype>
						<D:collection/>
					</D:resourcetype>
					<D:displayname>animals</D:displayname>
					<D:getetag>"8562d3318f5f3fc2c2d673be19e3a3e6"</D:getetag>
				</D:prop>
			</D:propstat>
		</D:response>
		<D:response>
			<D:href>http://localhost:4200/webdav/animals/Ram/</D:href>
			<D:propstat>
				<D:status>HTTP/1.1 200 OK</D:status>
				<D:prop>
					<D:getlastmodified>Wed, 28 Sep 2022 01:59:39 GMT</D:getlastmodified>
					<D:lockdiscovery/>
					<D:supportedlock>
						<D:lockentry>
							<D:lockscope>
								<D:exclusive/>
							</D:lockscope>
							<D:locktype>
								<D:write/>
							</D:locktype>
						</D:lockentry>
						<D:lockentry>
							<D:lockscope>
								<D:shared/>
							</D:lockscope>
							<D:locktype>
								<D:write/>
							</D:locktype>
						</D:lockentry>
					</D:supportedlock>
					<D:creationdate>2022-09-28T01:06:06+04:00</D:creationdate>
					<D:resourcetype>
						<D:collection/>
					</D:resourcetype>
					<D:displayname>Ram</D:displayname>
					<D:getetag>"2f39bd237e46587ee95afb43d18ce7ab"</D:getetag>
				</D:prop>
			</D:propstat>
		</D:response>
		<D:response>
			<D:href>http://localhost:4200/webdav/animals/Snail/</D:href>
			<D:propstat>
				<D:status>HTTP/1.1 200 OK</D:status>
				<D:prop>
					<D:getlastmodified>Wed, 28 Sep 2022 01:15:07 GMT</D:getlastmodified>
					<D:lockdiscovery/>
					<D:supportedlock>
						<D:lockentry>
							<D:lockscope>
								<D:exclusive/>
							</D:lockscope>
							<D:locktype>
								<D:write/>
							</D:locktype>
						</D:lockentry>
						<D:lockentry>
							<D:lockscope>
								<D:shared/>
							</D:lockscope>
							<D:locktype>
								<D:write/>
							</D:locktype>
						</D:lockentry>
					</D:supportedlock>
					<D:creationdate>2022-09-28T01:09:43+04:00</D:creationdate>
					<D:resourcetype>
						<D:collection/>
					</D:resourcetype>
					<D:displayname>Snail</D:displayname>
					<D:getetag>"9914f1531c9527dd416fb6f75b617317"</D:getetag>
				</D:prop>
			</D:propstat>
		</D:response>
		<D:response>
			<D:href>http://localhost:4200/webdav/animals/josh.jpg</D:href>
			<D:propstat>
				<D:status>HTTP/1.1 200 OK</D:status>
				<D:prop>
					<D:getlastmodified>Sat, 24 Sep 2022 23:23:27 GMT</D:getlastmodified>
					<D:lockdiscovery/>
					<D:supportedlock>
						<D:lockentry>
							<D:lockscope>
								<D:exclusive/>
							</D:lockscope>
							<D:locktype>
								<D:write/>
							</D:locktype>
						</D:lockentry>
						<D:lockentry>
							<D:lockscope>
								<D:shared/>
							</D:lockscope>
							<D:locktype>
								<D:write/>
							</D:locktype>
						</D:lockentry>
					</D:supportedlock>
					<D:creationdate>2022-09-28T01:36:28+04:00</D:creationdate>
					<D:resourcetype/>
					<D:displayname>josh.jpg</D:displayname>
					<D:getetag>"81b7f8ec3e03acd1da101c7ad460edc7"</D:getetag>
					<D:getcontentlength>3981912</D:getcontentlength>
					<D:getcontenttype>image/jpeg</D:getcontenttype>
				</D:prop>
			</D:propstat>
		</D:response>
		<D:response>
			<D:href>http://localhost:4200/webdav/animals/Ram/10678234286_f42986b005_k.Full%20Curl%20by%20Intermountain%20Region%20US%20Forest%20Service.jpg</D:href>
			<D:propstat>
				<D:status>HTTP/1.1 200 OK</D:status>
				<D:prop>
					<D:getlastmodified>Wed, 28 Sep 2022 01:06:50 GMT</D:getlastmodified>
					<D:lockdiscovery/>
					<D:supportedlock>
						<D:lockentry>
							<D:lockscope>
								<D:exclusive/>
							</D:lockscope>
							<D:locktype>
								<D:write/>
							</D:locktype>
						</D:lockentry>
						<D:lockentry>
							<D:lockscope>
								<D:shared/>
							</D:lockscope>
							<D:locktype>
								<D:write/>
							</D:locktype>
						</D:lockentry>
					</D:supportedlock>
					<D:creationdate>2022-09-28T01:06:50+04:00</D:creationdate>
					<D:resourcetype/>
					<D:displayname>10678234286_f42986b005_k.Full Curl by Intermountain Region US Forest Service.jpg</D:displayname>
					<D:getetag>"3b36baaced7b300b61aadcdea3d9813d"</D:getetag>
					<D:getcontentlength>566156</D:getcontentlength>
					<D:getcontenttype>image/jpeg</D:getcontenttype>
				</D:prop>
			</D:propstat>
		</D:response>
		<D:response>
			<D:href>http://localhost:4200/webdav/animals/Ram/9184032889_baeef0f143_k.full-curl%20ram%20in%20Denali%20National%20Park%20and%20Preserve.jpg</D:href>
			<D:propstat>
				<D:status>HTTP/1.1 200 OK</D:status>
				<D:prop>
					<D:getlastmodified>Wed, 28 Sep 2022 01:08:10 GMT</D:getlastmodified>
					<D:lockdiscovery/>
					<D:supportedlock>
						<D:lockentry>
							<D:lockscope>
								<D:exclusive/>
							</D:lockscope>
							<D:locktype>
								<D:write/>
							</D:locktype>
						</D:lockentry>
						<D:lockentry>
							<D:lockscope>
								<D:shared/>
							</D:lockscope>
							<D:locktype>
								<D:write/>
							</D:locktype>
						</D:lockentry>
					</D:supportedlock>
					<D:creationdate>2022-09-28T01:08:10+04:00</D:creationdate>
					<D:resourcetype/>
					<D:displayname>9184032889_baeef0f143_k.full-curl ram in Denali National Park and Preserve.jpg</D:displayname>
					<D:getetag>"113d2ab9abf31294f3c155fd1dd641a5"</D:getetag>
					<D:getcontentlength>231424</D:getcontentlength>
					<D:getcontenttype>image/jpeg</D:getcontenttype>
				</D:prop>
			</D:propstat>
		</D:response>
		<D:response>
			<D:href>http://localhost:4200/webdav/animals/Ram/9186263568_7f753ed399_k.full%20curl%20ram%20in%20Denali%20National%20Park%20and%20Preserve.jpg</D:href>
			<D:propstat>
				<D:status>HTTP/1.1 200 OK</D:status>
				<D:prop>
					<D:getlastmodified>Wed, 28 Sep 2022 01:07:38 GMT</D:getlastmodified>
					<D:lockdiscovery/>
					<D:supportedlock>
						<D:lockentry>
							<D:lockscope>
								<D:exclusive/>
							</D:lockscope>
							<D:locktype>
								<D:write/>
							</D:locktype>
						</D:lockentry>
						<D:lockentry>
							<D:lockscope>
								<D:shared/>
							</D:lockscope>
							<D:locktype>
								<D:write/>
							</D:locktype>
						</D:lockentry>
					</D:supportedlock>
					<D:creationdate>2022-09-28T01:07:38+04:00</D:creationdate>
					<D:resourcetype/>
					<D:displayname>9186263568_7f753ed399_k.full curl ram in Denali National Park and Preserve.jpg</D:displayname>
					<D:getetag>"56cdc40ff72d6e1f7d05b6b36581c079"</D:getetag>
					<D:getcontentlength>210557</D:getcontentlength>
					<D:getcontenttype>image/jpeg</D:getcontenttype>
				</D:prop>
			</D:propstat>
		</D:response>
		<D:response>
			<D:href>http://localhost:4200/webdav/animals/Snail/40001698461_0457172843_k.Motel%20Snails.jpg</D:href>
			<D:propstat>
				<D:status>HTTP/1.1 200 OK</D:status>
				<D:prop>
					<D:getlastmodified>Wed, 28 Sep 2022 01:10:54 GMT</D:getlastmodified>
					<D:lockdiscovery/>
					<D:supportedlock>
						<D:lockentry>
							<D:lockscope>
								<D:exclusive/>
							</D:lockscope>
							<D:locktype>
								<D:write/>
							</D:locktype>
						</D:lockentry>
						<D:lockentry>
							<D:lockscope>
								<D:shared/>
							</D:lockscope>
							<D:locktype>
								<D:write/>
							</D:locktype>
						</D:lockentry>
					</D:supportedlock>
					<D:creationdate>2022-09-28T01:10:53+04:00</D:creationdate>
					<D:resourcetype/>
					<D:displayname>40001698461_0457172843_k.Motel Snails.jpg</D:displayname>
					<D:getetag>"5097a689b8d4c6b975678cdebd08dfbf"</D:getetag>
					<D:getcontentlength>923862</D:getcontentlength>
					<D:getcontenttype>image/jpeg</D:getcontenttype>
				</D:prop>
			</D:propstat>
		</D:response>
		<D:response>
			<D:href>http://localhost:4200/webdav/animals/Snail/48490105071_1070413a77_k.aquatic%20snail.jpg</D:href>
			<D:propstat>
				<D:status>HTTP/1.1 200 OK</D:status>
				<D:prop>
					<D:getlastmodified>Wed, 28 Sep 2022 01:09:38 GMT</D:getlastmodified>
					<D:lockdiscovery/>
					<D:supportedlock>
						<D:lockentry>
							<D:lockscope>
								<D:exclusive/>
							</D:lockscope>
							<D:locktype>
								<D:write/>
							</D:locktype>
						</D:lockentry>
						<D:lockentry>
							<D:lockscope>
								<D:shared/>
							</D:lockscope>
							<D:locktype>
								<D:write/>
							</D:locktype>
						</D:lockentry>
					</D:supportedlock>
					<D:creationdate>2022-09-28T01:09:37+04:00</D:creationdate>
					<D:resourcetype/>
					<D:displayname>48490105071_1070413a77_k.aquatic snail.jpg</D:displayname>
					<D:getetag>"9c476ee05ba021d3c9068d59587e40ed"</D:getetag>
					<D:getcontentlength>429041</D:getcontentlength>
					<D:getcontenttype>image/jpeg</D:getcontenttype>
				</D:prop>
			</D:propstat>
		</D:response>
	</D:multistatus>`